language: node_js
node_js:
  - "0.12"   
  - "iojs-v1"
  - "iojs-v2"
sudo: false
script: "make test-travis"
before_script:
  - mysql -e 'create database minicloud_test;use minicloud_test;source ./lib/database/mysql.sql;'
  - "if [ -e '/usr/bin/iojs' ]; then node ./test/index-test.js &  else  node --harmony-generators ./test/index-test.js & fi"
  - "sleep 5"
  - "whereis iojs"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
