language: node_js
node_js:
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
sudo: required
script: "make test-travis"
before_script:
  - mysql -e 'create database minicloud_test;use minicloud_test;source ./lib/database/mysql.sql;'
  - "node index-test.js" 
  - "wget http://127.0.0.1:8031" 
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
