language: node_js
node_js:
  - "0.12"   
  - "1"
  - "2" 
  - "3"
  - "4"
sudo: true
cache:
  directories:
    - node_modules
before_install:
  - npm i --global
  - sudo apt-get install libpq-dev
addons:
  postgresql: "9.4"

before_script: 
  - mysql -e 'create database minicloud_test;'
  - psql -c 'create database minicloud_test;' -U postgres
  - "psql minicloud_test -c 'create extension postgis;' -U postgres"

script: "make test-travis"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
